In [1]:
import numpy as np
import pandas as pd

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("bollywood1to950.csv")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     950 non-null    object
 1   Year     840 non-null    object
 2   Rating   577 non-null    float64
 3   Runtime  630 non-null    float64
 4   Votes    577 non-null    float64
dtypes: float64(3), object(2)
memory usage: 37.2+ KB

In [6]:
df.drop('Year',axis=1,inplace=True)

In [8]:
df.head()

                       Name  Rating  Runtime     Votes
0               Skater Girl     6.6    107.0    1122.0
1                     Radhe     1.8    135.0  162353.0
2           Soorarai Pottru     9.1    153.0   82987.0
3  Sandeep Aur Pinky Faraar     6.3    125.0    6480.0
4           The White Tiger     7.1    125.0   49865.0

In [9]:
df.describe()

           Rating     Runtime          Votes
count  577.000000  630.000000     577.000000
mean     6.208492  116.747619    4528.963605
std      1.671071   25.197183   12431.215077
min      1.100000   37.000000       5.000000
25%      5.200000  100.000000      50.000000
50%      6.500000  119.000000     498.000000
75%      7.400000  134.750000    3770.000000
max      9.700000  261.000000  162353.000000

In [16]:
df=df.dropna()

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
MS=MinMaxScaler()
features=MS.fit_transform(df.drop('Name',axis=1))

In [20]:
from sklearn.metrics.pairwise import cosine_similarity

In [21]:
similarity=cosine_similarity(features)

In [22]:
cosine_df=pd.DataFrame(similarity,index=df['Name'],columns=df['Name'])

In [23]:
cosine_df

Name,Skater Girl,Radhe,Soorarai Pottru,Sandeep Aur Pinky Faraar,The White Tiger,Tumbbad,Sardar Ka Grandson,Hotel Mumbai,Koi Jaane Na,Andhadhun,...,Gunwali Dulhaniya,Taanashah,Fukrey Boyzzz: Space Mein Fukrapanti,No Man's Truth,Ishq Tera,Kehta Hai Yeh Dil,Mera Ramrajya Nai Kranti,Veergati,Rescue,Umakant Pandey Purush Ya
Name,,,,,,,,,,,,,,,,,,,,,
Skater Girl,1.000000,0.234423,0.902062,0.990794,0.933502,0.971171,0.889703,0.928012,0.831925,0.892070,...,0.908557,0.997017,0.965604,0.993176,0.982580,0.883425,0.992496,0.957455,0.999413,0.998867
Radhe,0.234423,1.000000,0.623852,0.315499,0.562858,0.391735,0.384061,0.566069,0.370124,0.638786,...,0.338331,0.200439,0.134714,0.261180,0.280794,0.348758,0.262691,0.123902,0.214951,0.240368
Soorarai Pottru,0.902062,0.623852,1.000000,0.921734,0.996796,0.961047,0.845781,0.997269,0.785095,0.999686,...,0.842652,0.890351,0.850325,0.899295,0.894166,0.823286,0.898981,0.841245,0.895316,0.899998
Sandeep Aur Pinky Faraar,0.990794,0.315499,0.921734,1.000000,0.949147,0.959027,0.940942,0.939541,0.894725,0.911827,...,0.952901,0.977653,0.923232,0.998371,0.996691,0.934469,0.998410,0.911534,0.985583,0.995164
The White Tiger,0.933502,0.562858,0.996796,0.949147,1.000000,0.976046,0.870189,0.999028,0.810011,0.994600,...,0.870802,0.922598,0.882036,0.930927,0.925294,0.850509,0.930589,0.872755,0.927528,0.931979
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kehta Hai Yeh Dil,0.883425,0.348758,0.823286,0.934469,0.850509,0.807578,0.999037,0.826957,0.994922,0.810555,...,0.998393,0.844995,0.731384,0.931935,0.955067,1.000000,0.933986,0.710790,0.867579,0.904357
Mera Ramrajya Nai Kranti,0.992496,0.262691,0.898981,0.998410,0.930589,0.949178,0.938215,0.920136,0.893340,0.887888,...,0.952735,0.980293,0.926776,0.999984,0.997922,0.933986,1.000000,0.915201,0.987997,0.997148
Veergati,0.957455,0.123902,0.841245,0.911534,0.872755,0.957752,0.720207,0.878742,0.636503,0.833768,...,0.749512,0.976777,0.999558,0.917482,0.887334,0.710790,0.915201,1.000000,0.966469,0.943005
Rescue,0.999413,0.214951,0.895316,0.985583,0.927528,0.971942,0.873887,0.923164,0.813206,0.885383,...,0.894369,0.999043,0.973674,0.988861,0.975991,0.867579,0.987997,0.966469,1.000000,0.996837
Umakant Pandey Purush Ya,0.998867,0.240368,0.899998,0.995164,0.931979,0.963210,0.909624,0.924474,0.856884,0.889443,...,0.927090,0.992406,0.952480,0.997562,0.990214,0.904357,0.997148,0.943005,0.996837,1.000000

In [33]:
def recommend_bollywood_movies(movie_name):
    print("Movie recommendation for:",movie_name)
    x=1
    for i in cosine_df['Race 3'].sort_values(ascending=False)[1:].head(5).index:
        print(f'{x} {i}')
        x+=1

In [34]:
recommend_bollywood_movies('Race 3')

Movie recommendation for: Race 3
1 Laxmii
2 Student of the Year 2
3 Coolie No. 1
4 Baaghi 3
5 Dabangg 3